version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.9
      commands:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 682033469251.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t abcallmobile .
      - docker tag abcallmobile:latest 682033469251.dkr.ecr.us-east-1.amazonaws.com/abcallmobile:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 682033469251.dkr.ecr.us-east-1.amazonaws.com/abcallmobile:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-abcall-mobile","682033469251.dkr.ecr.us-east-1.amazonaws.com/abcallmobile:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"682033469251.dkr.ecr.us-east-1.amazonaws.com/abcallmobile:latest"}' > imageDetail.json
      - cat imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      base-directory:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
